import { AccessibleDialogDemo, AccessibleFlowSummary } from "./components/accessibility-system";
import { Button, Card, FlowConnector, FlowNode, InputField, SelectField, Tabs } from "./components/flowone";
import { CompactFlow } from "./components/flow-system";
import { DataChart, Forecast, ProductAI, ProductKPI, ProductTable } from "./components/product-ui";
import { WebsiteHeader } from "./components/navigation-system";

const responsiveChecks = ["Header","Hero architecture","Flow","Living Transaction","Product UI","AI","Charts","Cards","CTA","Footer"];
const accessChecks = ["Keyboard","Visible focus","Contrast","Screen reader semantics","Reduced motion","Touch targets","Form labels","Error states","Status states","Heading hierarchy","Link / button semantics"];

function ValidationDoc({ index,title,note,children,dark=false }: { index:string;title:string;note:string;children:React.ReactNode;dark?:boolean }) {
  return <section className={`validation-doc ${dark?"is-dark":""}`}><header><span>{index}</span><div role="heading" aria-level={3}>{title}</div><p>{note}</p></header><div className="validation-stage">{children}</div></section>;
}

export default function StepNine() {
  return <div id="step-nine-content" className="step-nine">
    <section className="validation-intro"><div className="container-wide"><span>STEP 09 · 11 — RESPONSIVE + ACCESSIBILITY</span><div role="heading" aria-level={2}>Recompose.<br />Preserve meaning.</div><p>A final production-readiness pass across viewport, input method, motion preference, content length and data variation.</p><div className="validation-pillars">{["DESKTOP · PRECISE","TABLET · ADAPTED","MOBILE · RECOMPOSED","ACCESSIBILITY · EXPLICIT"].map(x=><span key={x}>{x}</span>)}</div></div></section>
    <div className="validation-body container-wide">
      <ValidationDoc index="01" title="Breakpoints" note="Five checkpoints with fluid behavior between them."><div className="breakpoint-validation">{[["390","Mobile","4 cols · 16 gutter · 20 padding"],["768","Tablet","8 cols · 20 gutter · 24 padding"],["1024","Compact desktop","8–12 cols · adapted"],["1280","Desktop","12 cols · 24 gutter"],["1440+","Wide","1280 max · breathing room"]].map(([size,name,rule])=><div key={size}><i/><strong>{size}</strong><span>{name}</span><small>{rule}</small></div>)}</div></ValidationDoc>
      <ValidationDoc index="02" title="Container Validation" note="Existing full, wide, standard and narrow containers retain protected edges."><div className="container-validation">{[["Full","100%"],["Wide","1280"],["Standard","1200"],["Narrow","760"]].map(([a,b])=><div className={`container-test is-${a.toLowerCase()}`} key={a}><span>{a}</span><b>{b}</b></div>)}</div></ValidationDoc>
      <ValidationDoc index="03" title="Typography Responsive" note="Editorial hierarchy scales while body and product type remain readable."><div className="type-validation"><div><span>DISPLAY · clamp(48px, 5.28vw, 76px)</span><strong>Connected consequence.</strong></div><div><span>SECTION · clamp(36px, 3.34vw, 48px)</span><b>One intelligent flow.</b></div><p>Body copy remains readable between 16–18px on mobile and 17–20px on larger screens.</p></div></ValidationDoc>
      <ValidationDoc index="04" title="Header Responsive" note="Logo, demo CTA and menu stay visible without excessive mobile height."><div className="validation-device-grid"><div className="device-desktop"><span>1440</span><WebsiteHeader /></div><div className="device-tablet"><span>768</span><WebsiteHeader /></div><div className="device-mobile"><span>390</span><WebsiteHeader forceMobile /></div></div></ValidationDoc>
      <ValidationDoc index="05" title="Navigation Responsive" note="Multi-column desktop navigation becomes reduced tablet navigation and tap accordions."><div className="navigation-validation"><div><span>DESKTOP</span><WebsiteHeader initialMenu="Platform" /></div><div className="mobile-nav-validation"><span>MOBILE · CLICK TO OPEN</span><WebsiteHeader forceMobile /></div></div></ValidationDoc>
      <ValidationDoc index="06" title="Flow Responsive" note="Reading order and node size remain clear when direction changes."><div className="responsive-flow-validation"><div><span>DESKTOP · LEFT TO RIGHT</span><div>{["ORDER","INVENTORY","INVOICE","GST","RECEIVABLE","COLLECTION","BANK","CASH"].map((x,i,a)=><div key={x}><FlowNode label={x} state={i<3?"complete":i===3?"active":"idle"} />{i<a.length-1&&<FlowConnector state={i<3?"completed":"inactive"} />}</div>)}</div></div><div className="flow-mobile-validation"><span>MOBILE · TOP TO BOTTOM</span><div>{["ORDER","INVOICE","GST","RECEIVABLE","CASH"].map((x,i,a)=><div key={x}><FlowNode label={x} state={i<2?"complete":i===2?"active":"idle"} />{i<a.length-1&&<FlowConnector vertical state={i<2?"completed":"inactive"} />}</div>)}</div></div></div><AccessibleFlowSummary stages={["Order","Inventory","Invoice","GST","Receivable","Collection","Bank","Cash"]} /></ValidationDoc>
      <ValidationDoc index="07" title="Living Transaction Responsive" note="Desktop may pin later; mobile is always a continuous sequential narrative."><div className="living-responsive-validation"><div><span>DESKTOP COMPOSITION</span><aside><b>03 / 10</b><strong>Invoice</strong><p>Transaction context remains stable while product state changes.</p></aside><main><FlowNode label="INVOICE" value="₹5,90,000" meta="TXN-10482" state="active" /></main></div><div className="living-mobile-validation"><span>MOBILE SEQUENCE</span>{[["ORDER","₹5,00,000 · Completed"],["INVOICE","₹5,90,000 · GST ₹90,000"],["AI","92% probability · Prioritize collection"]].map(([a,b],i)=><div key={a}><FlowNode label={a} meta={b} state={i===2?"predictive":"complete"} />{i<2&&<FlowConnector vertical state="completed" />}</div>)}</div></div></ValidationDoc>
      <ValidationDoc index="08" title="Product UI Responsive" note="Mobile rows retain invoice, amount, status and action; secondary detail remains accessible."><div className="product-responsive-validation"><div><span>DESKTOP TABLE</span><ProductTable /></div><div className="mobile-product-table"><span>MOBILE PRIORITY LIST</span><ProductTable /></div></div></ValidationDoc>
      <ValidationDoc index="09" title="AI Responsive" note="Insight, evidence, confidence and action stack without losing meaning."><div className="ai-responsive-grid"><ProductAI type="insight"/><ProductAI type="recommendation"/><ProductAI type="prediction"/><ProductAI type="action"/></div></ValidationDoc>
      <ValidationDoc index="10" title="Charts Responsive" note="Visuals simplify, while accessible summaries preserve exact meaning."><div className="chart-responsive-grid"><DataChart/><Forecast/></div><div className="chart-summary"><strong>Accessible summaries</strong><p>Cash position increased to ₹12.4 crore. A delayed payment may reduce expected cash by ₹5,90,000.</p></div></ValidationDoc>
      <ValidationDoc index="11" title="Forms Responsive" note="Labels, descriptions and errors are programmatically associated; mobile fields become single-column."><div className="form-validation"><InputField/><InputField state="error"/><SelectField state="selected"/><SelectField state="error"/><Button>Save changes</Button></div></ValidationDoc>
      <ValidationDoc index="12" title="Drawers / Modals" note="Desktop dialog centers; mobile becomes a near-full-width sheet with trapped focus and Escape close."><AccessibleDialogDemo /></ValidationDoc>
      <ValidationDoc index="13" title="Mobile Composition" note="Hierarchy is intentionally reordered instead of uniformly reduced."><div className="mobile-composition"><span>390 · NARRATIVE ORDER</span>{["Headline","Supporting context","Primary action","Flow state","Product detail","AI recommendation","Consequence"].map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span></div>)}</div></ValidationDoc>
      <ValidationDoc index="14" title="Accessibility States" note="Status and intelligence combine label, icon, structure and content—not color alone."><div className="access-state-grid"><div><span>STATUS</span><strong>Overdue</strong><p>Invoice due 4 days ago</p></div><div><span>AI PREDICTION</span><strong>92% probability</strong><p>Expected within 4 days</p></div><div><span>ERROR</span><strong>Bank connection unavailable</strong><p>Reconnect to synchronize transactions.</p></div><div><span>SUCCESS</span><strong>Payment reconciled</strong><p>Matched to INV-10482</p></div></div></ValidationDoc>
      <ValidationDoc index="15" title="Keyboard States" note="Logical sequence, explicit focus and focus restoration form the interaction contract."><div className="keyboard-validation">{[["Tab","Move forward"],["Shift + Tab","Move backward"],["Enter / Space","Activate control"],["Escape","Close overlay and restore focus"],["Arrow keys","Only within familiar composite controls"]].map(([a,b])=><div key={a}><kbd>{a}</kbd><span>{b}</span></div>)}</div></ValidationDoc>
      <ValidationDoc index="16" title="Reduced Motion" note="Movement is removed while final state, hierarchy and progress remain."><div className="reduced-validation">{[["Flow Pulse","Static active connector"],["Living Transaction","Sequential content"],["Pinned story","Normal document flow"],["Count-up","Final number"],["Chart draw","Complete chart"],["Parallax","No offset"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><code>prefers-reduced-motion: reduce</code></ValidationDoc>
      <ValidationDoc index="17" title="Content Stress Tests" note="Long entities, statuses and destinations wrap without breaking hierarchy."><div className="content-stress-grid"><Card title="Ananya Enterprises Private Limited">Long company names wrap naturally while preserving action and metadata.</Card><div className="stress-nav"><span>NAVIGATION LABEL</span><strong>Accounts Receivable and Collection Intelligence</strong></div><div className="stress-status"><span>STATUS</span><strong>Pending additional compliance documentation</strong></div><InputField state="filled" label="Customer purchase order reference and internal authorization number"/></div></ValidationDoc>
      <ValidationDoc index="18" title="Data Stress Tests" note="Tabular numerals, wrapping and explicit fallbacks support varied values."><div className="data-stress-grid">{[["Standard","₹5,90,000"],["Crore","₹12.4 Cr"],["Large","₹1,24,56,78,900"],["Probability","0% · 92% · 100%"],["Negative","−₹8,40,000"],["Missing","—"],["Loading","Loading…"],["Error","Unavailable"]].map(([a,b])=><ProductKPI key={a} label={a.toUpperCase()} value={b} type={a==="Error"?"alert":"standard"}/>)}</div></ValidationDoc>
      <ValidationDoc index="19" title="Responsive QA Matrix" note="Required checkpoints for implementation and Elementor review."><QAMatrix columns={["390","768","1024","1280","1440+"]} rows={responsiveChecks}/></ValidationDoc>
      <ValidationDoc index="20" title="Accessibility QA Matrix" note="WCAG 2.2 AA acceptance criteria for every release." dark><QAMatrix columns={["Requirement","Desktop","Tablet","Mobile"]} rows={accessChecks} dark/></ValidationDoc>
    </div>
  </div>;
}

function QAMatrix({columns,rows,dark=false}:{columns:string[];rows:string[];dark?:boolean}) {
  return <div className={`qa-matrix ${dark?"is-dark":""}`}><div className="qa-head"><strong>TEST</strong>{columns.map(x=><strong key={x}>{x}</strong>)}</div>{rows.map(row=><div key={row}><span>{row}</span>{columns.map(column=><span key={column}><i/>PASS</span>)}</div>)}</div>;
}
